// App
export const LOAD_APP_DATA = "LOAD_APP_DATA";

// Auth
export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";
export const FETCH_BLOCK_LIST = "FETCH_BLOCK_LIST";
export const FETCH_BLOCK_LIST_SUCCESS = "FETCH_BLOCK_LIST_SUCCESS";
export const REGISTER_FCM_TOKEN = "REGISTER_FCM_TOKEN";
export const REGISTER_FCM_TOKEN_SUCCESS = "REGISTER_FCM_TOKEN_SUCCESS";
export const BLOCK_USER = "BLOCK_USER";
export const UNBLOCK_USER = "UNBLOCK_USER";
export const GET_USERNAME_AMOUNTSUM = "GET_USERNAME_AMOUNTSUM";
export const GET_USERNAME_AMOUNTSUM_SUCCESS = "GET_USERNAME_AMOUNTSUM_SUCCESS";

// Store
export const STORE_FETCH_ENERGY = "STORE_FETCH_ENERGY";
export const STORE_FETCH_ENERGY_SUCCESS = "STORE_FETCH_ENERGY_SUCCESS";
export const STORE_FETCH_COIN = "STORE_FETCH_COIN";
export const STORE_FETCH_COIN_SUCCESS = "STORE_FETCH_COIN_SUCCESS";
export const GET_GAME_ITEMS = "GET_GAME_ITEMS";
export const GET_GAME_ITEMS_SUCCESS = "GET_GAME_ITEMS_SUCCESS";
export const PURCHASE_ITEMS = "PURCHASE_ITEMS";
export const PURCHASE_ITEMS_SUCCESS = "PURCHASE_ITEMS_SUCCESS";
export const GET_PURCHASED_ITEMS = "GET_PURCHASED_ITEMS";
export const GET_PURCHASED_ITEMS_SUCCESS = "GET_PURCHASED_ITEMS_SUCCESS";
export const PURCHASE_ENERGY = "PURCHASE_ENERGY";

// Game
export const GAME_FETCH_TOURNAMENT_CLASSES = "GAME_FETCH_TOURNAMENT_CLASSES";
export const GAME_FETCH_TOURNAMENT_CLASSES_SUCCESS = "GAME_FETCH_TOURNAMENT_CLASSES_SUCCESS";
export const GAME_FETCH_GAME_LIST = "GAME_FETCH_GAME_LIST";
export const GAME_FETCH_GAME_LIST_SUCCESS = "GAME_FETCH_GAME_LIST_SUCCESS";
export const GAME_FETCH_TOURNAMENT_PLAYABLE = "GAME_FETCH_TOURNAMENT_PLAYABLE";
export const GAME_FETCH_TOURNAMENT_RANKING = "GAME_FETCH_TOURNAMENT_RANKING";
export const GAME_FETCH_TOURNAMENT_HISTORY = "GAME_FETCH_TOURNAMENT_RANKING_HISTORY";
export const GAME_JOIN_TOURNAMENT = "GAME_JOIN_TOURNAMENT";
export const GAME_FETCH_GAME_AUTH_TOKEN = "GAME_FETCH_GAME_AUTH_TOKEN";
export const GAME_FETCH_GAME_PLAY_STATUS = "GAME_FETCH_GAME_PLAY_STATUS";
export const GAME_FETCH_GAME_TOURNAMENTS = "GAME_FETCH_GAME_TOURNAMENTS";
export const GAME_FETCH_GAME_MATCHES = "GAME_FETCH_GAME_MATCHES";
export const GAME_MATCH_START_SESSION = "GAME_MATCH_START_SESSION";
export const GAME_MATCH_START_PAIRING = "GAME_MATCH_START_PAIRING";
export const GAME_FETCH_MATCH_RESULT = "GAME_FETCH_MATCH_RESULT";

// Chat
export const CHAT_FETCH_THREADS = "CHAT_FETCH_PUBLIC_THREADS";
export const CHAT_FETCH_THREADS_SUCCESS = "CHAT_FETCH_PUBLIC_THREADS_SUCCESS";
export const CHAT_FETCH_THREAD_MESSAGES = "CHAT_FETCH_THREAD_MESSAGES";
export const CHAT_SET_THREAD_READ_AT = "CHAT_SET_THREAD_READ_AT";
export const CHAT_FETCH_THREAD_UNREAD_MESSAGE_COUNT = "CHAT_FETCH_THREAD_UNREAD_MESSAGE_COUNT";
export const CHAT_FETCH_THREAD_UNREAD_MESSAGE_COUNT_SUCCESS = "CHAT_FETCH_THREAD_UNREAD_MESSAGE_COUNT_SUCCESS";
export const CHAT_SEND_MESSAGE = "CHAT_SEND_MESSAGE";
export const CHAT_BLOCK_CHECK = "CHAT_BLOCK_CHECK";
export const CHAT_CREATE_SUPPORT_THREAD = "CHAT_CREATE_SUPPORT_THREAD";
export const CHAT_CREATE_SUPPORT_THREAD_SUCCESS = "CHAT_CREATE_SUPPORT_THREAD_SUCCESS";
export const CHAT_SEND_DIRECT_MESSAGE = "CHAT_SEND_DIRECT_MESSAGE";
export const CHAT_SEND_DIRECT_MESSAGE_SUCCESS = "CHAT_SEND_DIRECT_MESSAGE_SUCCESS";

//Profile
export const GET_USER_TOURNAMENT_HISTORY = "USER_GET_TOURNAMENT_HISTORY";
export const GET_USER_TOURNAMENT_HISTORY_SUCCESS = "USER_GET_TOURNAMENT_HISTORY_SUCCESS";
export const PROFILE_SUSPEND = "PROFILE_SUSPEND";